version: "3.4"

services:
  #
  # DATABASES
  #

  mysql:
    container_name: "graphql-node-mysql"
    image: mysql:5.7.26
    environment:
      MYSQL_ROOT_PASSWORD: "hard2guess"
      MYSQL_DATABASE: "graphql-blog-api"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:62001:3306"
    command:
      [
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION",
      ]
    restart: unless-stopped

volumes:
  mysql-data:
    name: graphql-node-mysql-data
